### ISSUE TITLE
First release checklist

### ISSUE THREAD

**Issue by NatalieZelenka** [NatalieThurlby/tidy-archive-catalogues#3]
Check list for first release:

- [ ] All basic infrastructure set up (with fun GitHub buttons where they exist)
    - [ ] Website/documentation (Sphinx)
        - [x] Basic config
        - [x] Autodoc (#2, fixed by #5)
        - [ ] Beautify (readthedocs template)
        - [ ] Change to coming from main branch
    - [ ] Citable (Zenodo)
    - [ ] Testing
        - [x] Pytest/GitHub actions
        - [ ] coverage.py (#8) 
    - [ ] Milestones/issues organising what will be done next, and linking to roadmap.
    - [x] Installable using `pip`
        - [x] pre-release set up
        - [ ] Github actions auto-release (#7)
- [ ] Date-cleaning functionality finished (1Ai, 2A) in [roadmap](https://nataliethurlby.github.io/tidy-archive-catalogues/_build/contents/roadmap.html)
    - [ ] Return potential mistakes
    - [ ] Output usable dates and date ranges for visualisation.
